### ISSUE TITLE
Error when install magefan blog site map with composer

### ISSUE THREAD

**Issue by leoho150899** [magefan/module-blog-sitemap#1]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires magefan/module-blog-sitemap ^2.0 -> satisfiable by magefan/module-blog-sitemap[2.0.0].
    - magefan/module-blog-sitemap 2.0.0 requires magento/module-blog * -> could not be found in any version, there may be a typo in the package name.

**Comment by leoho150899** [comment]
![image](https://github.com/magefan/module-blog-sitemap/assets/136664214/021602f3-43d0-4dcf-85b9-04c221bddca9)
It seems this issue comes from composer.json

**Comment by magefan** [comment]
@leoho150899 , thank you for your collaboration. The PR request has been approved and a new package version released.
